project:
  type: website

website:
  title: "Jackson Chou"
  navbar:
    pinned: true
    search: true
    right:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - icon: linkedin
        href: https://www.linkedin.com/in/jacksonchou/
      
  page-footer:
    left: "&#169; 2025 Jackson Chou"
    right: Made with ❤️ and [Quarto](https://quarto.org/)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    pagetitle: "Jackson Chou - {{< meta title >}}"
    smooth-scroll: true

