project:
  type: website

website:
  title: "Jackson Chou"
  site-url: https://jacksonchou.com
  repo-url: https://github.com/JacksonChou/jchou
  repo-actions:
    - source
    - issue
    
  navbar:
    pinned: true
    search: true
    right:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Experience
      - icon: linkedin
        href: https://www.linkedin.com/in/jacksonchou/
      - icon: github
        href: https://www.github.com/jacksonchou/jchou
      
  page-footer:
    left: "&#169; 2025 Jackson Chou"
    right: Made with ❤️ and [Quarto](https://quarto.org/)

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    pagetitle: "{{< meta title >}}"
    smooth-scroll: true

execute:
  freeze: auto