project:
  type: website

website:
  title: "Jackson Chou"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

