project:
  type: website

website:
  title: "Jackson Chou"
  navbar:
    search: true
    right:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - icon: linkedin
        href: https://www.linkedin.com/in/jacksonchou/
      
page-footer:
  border: true
  left: "&#169; 2025 Jackson Chou"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual
