---
pagetitle: "Resume"
title: "Jackson Chou"
format:
  html:
    toc: true
  #pdf:
      #author: Jackson Chou
      #pdf-engine: pdflatex
    
css: cv.css

project-type: website
---

## EXPERIENCE

**New Relic**\
*Manager, People Analytics* [April 2021 --- Present]{.cvdate}

-   Develop and execute long-term strategy and roadmap for the People Analytics tech stack and its organizational adoption

-   Established data governance across the analytics platform, while managing the usage and engagement of dashboards and custom applications

-   Partner with cross-functional stakeholders (HRBP, DEI, TA) to develop talent strategies and new programs, ensuring success metrics are defined and aligned to business objectives

-   Led the growth of the analytics team, including hiring, onboarding and directly managing a data analyst

*Senior Data Analyst, People Analytics* [January 2018 --- March 2021]{.cvdate}

-   Led the implementation of a People Analytics platform (Visier) to scale self-service model

-   Develop full scale reporting on the employee lifecycle and manage quarterly business reviews, comp committee and ad-hoc analyses to highlight workforce trends

-   Automated data pipelines from Workday and built out data visualizations to improve operations efficiency

-   Develop enablement content and training curriculum to build up data literacy skills within the People team

**Logitech**\
*Senior Analyst, Market Analytics* [August 2014 --- January 2018]{.cvdate}

-   Analyze and drive key insights from multiple datasets on worldwide market dynamics, competitive landscape and trends to senior management, business groups, and cross-functional partners

-   Develop data visualizations (Tableau) and analytical tools to improve decision making, track new product introductions and performance

-   Create in-depth research analysis to support business group's strategic planning and goals

-   Provide analytical support during business reviews, product reviews, quarterly earnings and investor relation events

**Levi Strauss & Co.**\
*Analyst, Applied Analytics* [July 2013 --- May 2014]{.cvdate}

-   Transform business questions into actionable analysis for senior management, sales team and
planning team

-   Analyze POS data based on Retail Trade Area methodology to provide actionable recommendations
to improve product assortments, inventory levels, mitigate risk of product markdowns and identify
white space opportunities

-   Partner with wholesale accounts to implement and support Intelligent Clustering methodology for
optimal product mix at door level profiles

-   Developed and maintained analytical tools to build deeper insights and ensure wholesale accounts
are reactive to shifts in retail landscape

**Hanesbrands Inc.**\
*Supply Chain Intern, Advanced Modeling and Simulation* [June 2012 --- August 2012]{.cvdate}

-   Researched past literature optimization models and techniques

-   Formulated and developed a prototype Mixed Integer Nonlinear Optimization model

-   Data mined and collected historical sales data for model inputs

-   Presented the optimization model to senior managers and audiences with non-technical backgrounds

## EDUCATION

**Northeastern University**\
*Master of Science in Operations Research*[*May 2013*]{.cvdate}

**San Francisco State University**\
*Bachelor of Science in Business Administration*[*January 2010*]{.cvdate}\
Concentration: Decision Sciences, Corporate Finance\
Minor: Information Systems

## SKILLS

-   **Software** : Quarto, Posit Workbench, Tableau, Looker Studio, Visier, eqtble, AWS
-   **Languages** : R (tidyverse), SQL, $LaTeX$
